// Price History
export const BCH_PRICE_HISTORY_REQUESTED = 'BCH_PRICE_HISTORY_REQUESTED';
export const BCH_DATA_FETCH_SUCCEEDED = 'BCH_DATA_FETCH_SUCCEEDED';
export const BCH_DATA_FETCH_FAILED = 'BCH_DATA_FETCH_FAILED';

// Current Price
export const BCH_CURRENT_PRICE_REQUESTED = "BCH_CURRENT_PRICE_REQUESTED";
export const BCH_CURRENT_PRICE_SUCCESS = "BCH_CURRENT_PRICE_SUCCESS";
export const BCH_CURRENT_PRICE_FAIL = "BCH_CURRENT_PRICE_FAIL";

// Change range
export const CHANGE_RANGE_REQUESTED = 'CHANGE_RANGE_REQUESTED';
export const CHANGE_RANGE_SUCCESSFUL = 'CHANGE_RANGE_SUCCESSFUL';
export const CHANGE_RANGE_FAIL = 'CHANGE_RANGE_FAIL';

// News
export const GET_NEWS_FEED_REQUESTED = "GET_NEWS_FEED_REQUESTED"
export const GET_NEW_FEED_SUCCESS = "GET_NEW_FEED_SUCCESS"
export const GET_NEW_FEED_FAIL = "GET_NEW_FEED_FAIL"